// This file was auto-generated by ML.NET Model Builder.

using Microsoft.ML;
using Microsoft.ML.Data;

namespace XSLAPrepareData.Model
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"ToPlatform")]
            public string ToPlatform { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"FromPlatform")]
            public string FromPlatform { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"CustomerName")]
            public string CustomerName { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"AffectedVersion")]
            public string AffectedVersion { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"IsEscalationTeam")]
            public string IsEscalationTeam { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"CreatedMonth")]
            public float CreatedMonth { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"DaysSinceRelease")]
            public float DaysSinceRelease { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Severity")]
            public string Severity { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"Priority")]
            public float Priority { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"Initiative")]
            public string Initiative { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"ZVMZCAOsType")]
            public string ZVMZCAOsType { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"Component")]
            public string Component { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"NumberOfWorkingDays")]
            public float NumberOfWorkingDays { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"Sentimental")]
            public float Sentimental { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"UserImpact")]
            public string UserImpact { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"WhatIsNeeded")]
            public string WhatIsNeeded { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"Summary")]
            public string Summary { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"driver")]
            public string Driver { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"vra")]
            public string Vra { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"ghost_vra")]
            public float Ghost_vra { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"vpg")]
            public float Vpg { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"fol")]
            public float Fol { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"move")]
            public float Move { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"ssh")]
            public float Ssh { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"install")]
            public float Install { get; set; }

            [LoadColumn(25)]
            [ColumnName(@"host_logs")]
            public float Host_logs { get; set; }

            [LoadColumn(26)]
            [ColumnName(@"upgrade")]
            public float Upgrade { get; set; }

            [LoadColumn(27)]
            [ColumnName(@"crash")]
            public float Crash { get; set; }

            [LoadColumn(28)]
            [ColumnName(@"wa")]
            public float Wa { get; set; }

            [LoadColumn(29)]
            [ColumnName(@"fixed")]
            public float Fixed { get; set; }

            [LoadColumn(30)]
            [ColumnName(@"fully")]
            public float Fully { get; set; }

            [LoadColumn(31)]
            [ColumnName(@"env_is_ok")]
            public float Env_is_ok { get; set; }

            [LoadColumn(32)]
            [ColumnName(@"msp")]
            public float Msp { get; set; }

            [LoadColumn(33)]
            [ColumnName(@"vcd")]
            public float Vcd { get; set; }

            [LoadColumn(34)]
            [ColumnName(@"kicklock")]
            public float Kicklock { get; set; }

            [LoadColumn(35)]
            [ColumnName(@"ltr")]
            public float Ltr { get; set; }

            [LoadColumn(36)]
            [ColumnName(@"network")]
            public float Network { get; set; }

            [LoadColumn(37)]
            [ColumnName(@"Firewall")]
            public float Firewall { get; set; }

            [LoadColumn(38)]
            [ColumnName(@"proxy")]
            public float Proxy { get; set; }

            [LoadColumn(39)]
            [ColumnName(@"ProblematicPlatform")]
            public float ProblematicPlatform { get; set; }

            [LoadColumn(40)]
            [ColumnName(@"CustomerName_int")]
            public float CustomerName_int { get; set; }

            [LoadColumn(41)]
            [ColumnName(@"AffectedVersion_int")]
            public float AffectedVersion_int { get; set; }

            [LoadColumn(42)]
            [ColumnName(@"Initiative_int")]
            public float Initiative_int { get; set; }

            [LoadColumn(43)]
            [ColumnName(@"ZVMZCAOsType_int")]
            public float ZVMZCAOsType_int { get; set; }

            [LoadColumn(44)]
            [ColumnName(@"Component_int")]
            public float Component_int { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"ToPlatform")]
            public float[] ToPlatform { get; set; }

            [ColumnName(@"FromPlatform")]
            public float[] FromPlatform { get; set; }

            [ColumnName(@"CustomerName")]
            public float[] CustomerName { get; set; }

            [ColumnName(@"AffectedVersion")]
            public float[] AffectedVersion { get; set; }

            [ColumnName(@"IsEscalationTeam")]
            public float[] IsEscalationTeam { get; set; }

            [ColumnName(@"CreatedMonth")]
            public float CreatedMonth { get; set; }

            [ColumnName(@"DaysSinceRelease")]
            public float DaysSinceRelease { get; set; }

            [ColumnName(@"Severity")]
            public float[] Severity { get; set; }

            [ColumnName(@"Priority")]
            public float Priority { get; set; }

            [ColumnName(@"Initiative")]
            public float[] Initiative { get; set; }

            [ColumnName(@"ZVMZCAOsType")]
            public float[] ZVMZCAOsType { get; set; }

            [ColumnName(@"Component")]
            public float[] Component { get; set; }

            [ColumnName(@"NumberOfWorkingDays")]
            public float NumberOfWorkingDays { get; set; }

            [ColumnName(@"Sentimental")]
            public float Sentimental { get; set; }

            [ColumnName(@"UserImpact")]
            public float[] UserImpact { get; set; }

            [ColumnName(@"WhatIsNeeded")]
            public float[] WhatIsNeeded { get; set; }

            [ColumnName(@"Summary")]
            public float[] Summary { get; set; }

            [ColumnName(@"driver")]
            public float[] Driver { get; set; }

            [ColumnName(@"vra")]
            public float[] Vra { get; set; }

            [ColumnName(@"ghost_vra")]
            public float Ghost_vra { get; set; }

            [ColumnName(@"vpg")]
            public float Vpg { get; set; }

            [ColumnName(@"fol")]
            public float Fol { get; set; }

            [ColumnName(@"move")]
            public float Move { get; set; }

            [ColumnName(@"ssh")]
            public float Ssh { get; set; }

            [ColumnName(@"install")]
            public float Install { get; set; }

            [ColumnName(@"host_logs")]
            public float Host_logs { get; set; }

            [ColumnName(@"upgrade")]
            public float Upgrade { get; set; }

            [ColumnName(@"crash")]
            public float Crash { get; set; }

            [ColumnName(@"wa")]
            public float Wa { get; set; }

            [ColumnName(@"fixed")]
            public float Fixed { get; set; }

            [ColumnName(@"fully")]
            public float Fully { get; set; }

            [ColumnName(@"env_is_ok")]
            public float Env_is_ok { get; set; }

            [ColumnName(@"msp")]
            public float Msp { get; set; }

            [ColumnName(@"vcd")]
            public float Vcd { get; set; }

            [ColumnName(@"kicklock")]
            public float Kicklock { get; set; }

            [ColumnName(@"ltr")]
            public float Ltr { get; set; }

            [ColumnName(@"network")]
            public float Network { get; set; }

            [ColumnName(@"Firewall")]
            public float Firewall { get; set; }

            [ColumnName(@"proxy")]
            public float Proxy { get; set; }

            [ColumnName(@"ProblematicPlatform")]
            public float ProblematicPlatform { get; set; }

            [ColumnName(@"CustomerName_int")]
            public float CustomerName_int { get; set; }

            [ColumnName(@"AffectedVersion_int")]
            public float AffectedVersion_int { get; set; }

            [ColumnName(@"Initiative_int")]
            public float Initiative_int { get; set; }

            [ColumnName(@"ZVMZCAOsType_int")]
            public float ZVMZCAOsType_int { get; set; }

            [ColumnName(@"Component_int")]
            public float Component_int { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("Model/MLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
